name: untitled3
version: '${project.version}'
main: textplugin.untitled3.Untitled3
api-version: 1.19
commands:
  sethealth:
    description: set whatever health u want
    usage: /<command>
  spawnentity:
    description: spawn whatever animal or entity u want
    usage: /<command>
  flyspeed:
    description: controls fly speed
    usage: /<command>
  getentities:
    description: kill all entities
    usage: /<command>
  cleanentities:
    description: removes all entities that is not player
    usage: /<command>
  debugtest:
    description: dev tool
    usage: /<command>
  gravity:
    description: turns on/off gravity
    usage: /<command>
  fly:
    description: turns on/off fly
    usage: /<command>
  setarrowsbody:
    description: arrowsss on my body
    usage: /<command>
  setarrowscooldown:
    description: set arrows cooldown to be removed from your body
    usage: /<command>
  setwalkspeed:
    description: set your walkspeed to a determinate speed
    usage: /<command>
  playerlistnamechanger:
    description: changes your name at leaderboards (tab)
    usage: /<command>
  playerspickupitems:
    description: sets if player can pickup items or not
    usage: /<command>
