name: untitled3
version: '${project.version}'
main: textplugin.untitled3.Untitled3
api-version: 1.19
commands:
  sethealth:
    description: set whatever health u want
    usage: /<command>
  spawnentity:
    description: spawn whatever animal or entity u want
    usage: /<command>
  flyspeed:
    description: controls fly speed
    usage: /<command>
  getentities:
    description: kill all entities
    usage: /<command>
